"""Where `anchor3d(pick="visible")` puts every leader in the shipped figure.

`figures/drug_discovery.py` is the only place in the corpus that asks for
`pick="visible"`, and it asks eight times. The answer comes out of
`occlude._depth_grid`, a pure-Python rasterisation of the drawable faces, and
the backlog wants that rasterisation made faster. The reason it has not been
is that its output does not feed a boolean: it decides *which residue* a
leader touches, so a difference of one grid cell moves a line on the page.

So this pins it, and it pins two things rather than one.

The first is the eight anchors themselves, to the last bit. Any change to the
grid that moves one of these has changed the figure, and should be looked at
rather than discovered later in a corpus diff.

The second is the *shape of the decision*, which is the part that turned out
to be worth writing down. `_most_visible` scores a candidate by how many of
the nine cells around it show the same surface, so the score is an integer
from zero to nine and it saturates. Five of the eight features have between
two and nine candidates all sitting at nine, and the winner among them is
whichever `label_runs` happens to list first. There is no margin in the score
at all: the tie-break is iteration order. What protects the figure is not that
the best candidate is clearly best -- it is not -- but that knocking the
incumbent off nine takes a whole cell's worth of change, and the incumbents
are between a third and a fraction under one slack from their nearest flip.

That is the difference that matters for the rewrite the backlog wants. A
vectorised rasteriser that computes the same barycentric test on the same cell
centres will agree to the last bit and every anchor stays put; one that rounds
cell coverage differently -- a half-open edge rule, cell corners instead of
centres, a different tie between two triangles at one cell -- moves whole
cells, and five of these eight leaders will jump to another residue without
anything in the drawing looking obviously wrong. The pin is here so that jump
is a test failure and not a discovery.
"""

import sys
from pathlib import Path

import pytest

FIGURES = Path(__file__).resolve().parent.parent / "figures"
if str(FIGURES) not in sys.path:
    sys.path.insert(0, str(FIGURES))

target = pytest.importorskip("target")
dd = pytest.importorskip("drug_discovery")

import inklet.three
from inklet.three.api import _EMPTY, _SLACK, _front_grid

#: Feature name -> the index into its run that `pick="visible"` chooses, and
#: the page point that lands on, in millimetres. Regenerated by hand from
#: `tmp/agents/r6-three/pinvals.py` if the fold itself is ever re-posed.
EXPECTED = {
    "sheet": (3, (-4.537913929369166, -16.814666139582965)),
    "helix-c": (0, (17.974435980721264, -39.901454532877615)),
    "p-loop": (1, (18.31492159992031, -16.630001161402824)),
    "hinge": (0, (-13.91613257780004, -13.221685577798983)),
    "activation-loop": (0, (-0.5121368356445305, -11.161410280681483)),
    "c-lobe": (5, (-22.632851868798937, 17.53094074177742)),
    "n-lobe": (1, (-6.041712055841131, -28.1205508837035)),
    "ligand": (0, (-4.150529090371258, -8.398584699182445)),
}

#: Feature name -> (candidates offered, candidates the grid accepts as
#: unobstructed, the best score any of them reaches, how many reach it).
#: `helix-c` accepts none and falls back to the nearest candidate, which is
#: what `pick="nearest"` would have done; `sheet` accepts one.
DECISION = {
    "sheet": (7, 1, 6, 1),
    "helix-c": (16, 0, None, 0),
    "p-loop": (6, 4, 9, 3),
    "hinge": (5, 5, 9, 5),
    "activation-loop": (15, 5, 9, 3),
    "c-lobe": (19, 3, 9, 2),
    "n-lobe": (20, 12, 9, 9),
    "ligand": (1, 1, 7, 1),
}


@pytest.fixture(scope="module")
def kinase():
    """The wide panel's fold, anchors and all. Built once: it is not cheap."""
    return dd.fold(dd.WIDE)


def test_every_visible_anchor_in_the_corpus_lands_where_it_lands(kinase):
    """The eight leader targets, to the last bit."""
    got = {name: kinase.anchor_point(name) for name in EXPECTED}
    assert {name: (point.x, point.y) for name, point in got.items()} == \
        {name: place for name, (_, place) in EXPECTED.items()}


def test_the_anchor_chosen_is_the_residue_it_is_meant_to_be(kinase):
    """The same claim said in residues, which is what a reader would notice.

    The point above is what moves on the page; this is what it means. A leader
    that jumps from the fourth residue of a run to the eleventh is pointing at
    a different part of the protein, and the figure's caption does not change.
    """
    view = inklet.three.view_of(kinase)
    for name, run in target.label_runs().items():
        place = kinase.anchor_point(name)
        distances = [abs(view.project(inklet.three.Vec3(*p)).point.x - place.x)
                     + abs(view.project(inklet.three.Vec3(*p)).point.y - place.y)
                     for p in run]
        chosen = min(range(len(run)), key=distances.__getitem__)
        assert chosen == EXPECTED[name][0], name


def test_the_visible_pick_is_decided_by_a_tie_in_five_of_eight_cases(kinase):
    """The knife edge, written down as an assertion.

    Not a property anyone wants -- it is a finding. Five features offer two to
    nine candidates that all score the maximum nine, so `_most_visible`
    returns the earliest of them and nothing about the geometry says it should
    be that one. If a change to the depth grid alters these counts it has
    altered which candidates are in the running, and the anchors above are
    then landing where they land for a different reason even if they have not
    moved yet.
    """
    view = inklet.three.view_of(kinase)
    grid, x0, y0, step, wide, tall = _front_grid(kinase)
    slack = step * _SLACK

    summary = {}
    for name, run in target.label_runs().items():
        scores = []
        for candidate in run:
            at = view.project(inklet.three.Vec3(*candidate))
            cx = int((at.point.x - x0) / step)
            cy = int((at.point.y - y0) / step)
            if not (1 <= cx < wide - 1 and 1 <= cy < tall - 1):
                continue
            here = grid[cy * wide + cx]
            if here == _EMPTY or at.depth - here > slack:
                continue
            scores.append(sum(
                1 for dy in (-1, 0, 1) for dx in (-1, 0, 1)
                if abs(grid[(cy + dy) * wide + cx + dx] - here) < slack))
        best = max(scores, default=None)
        summary[name] = (len(run), len(scores), best,
                         sum(1 for s in scores if s == best) if scores else 0)

    assert summary == DECISION
    tied = sum(1 for _, _, _, count in summary.values() if count > 1)
    assert tied == 5


def test_the_grid_is_the_same_grid_on_a_second_ask(kinase):
    """`_front_grid` caches per node, and the cache is the contract.

    Eight anchors on one node means the rasterisation happens once and seven
    calls read it. A rewrite that made the grid cheaper but stopped caching it
    would be slower on this figure, not faster.
    """
    assert _front_grid(kinase) is _front_grid(kinase)
