"""Dates and clock time on an axis, ticked where a reader expects them.

A time axis is a linear scale with a different idea of a round number. `1, 2,
5` times a power of ten is right for a length and wrong for a month: the ladder
a reader divides in their head runs 1, 2, 5, 10, 15, 30 seconds, then the same
in minutes, then 1, 2, 3, 6, 12 hours, then days, weeks, months, quarters and
years -- and the units are not powers of each other, which is why
`nice_step` cannot be pointed at seconds and left to it.

Ticks are also *aligned*, not merely spaced. A monthly tick lands on the first
of the month, a weekly one on a Monday, an hourly one on the hour. A grid of
30-day intervals starting wherever the data happened to start is arithmetically
even and reads as noise.

    p = inklet.panel(60, 34, x=("2024-01-01", "2024-12-31"), y=(0, 40))
    p.line(series).axis("bottom")

A `(low, high)` pair of ISO strings or `datetime`s is recognised by `panel()`
itself, so the shorthand above builds one of these; `inklet.plot.dates(...)` is
the explicit spelling, and takes the same values.
"""

from __future__ import annotations

import calendar
import datetime as _dt
import math
from dataclasses import dataclass, replace
from typing import Sequence

from ..core import mm
from .scale import Range, Scale, ScaleError, _interpolate

__all__ = ["Time", "TimeStep", "dates", "to_time", "time_ticks"]

_EPOCH = _dt.datetime(1970, 1, 1)

_SECOND = 1.0
_MINUTE = 60.0
_HOUR = 3600.0
_DAY = 86400.0
_WEEK = 7 * _DAY

#: The ladder, coarse end last. `(unit, count, seconds)` -- the seconds are
#: only used to choose which rung to stand on; the ticks themselves are
#: generated by walking calendar units, because a month is not 2629746 seconds
#: and a tick on the 31st of February is not a tick.
_LADDER: tuple[tuple[str, int, float], ...] = (
    ("second", 1, _SECOND), ("second", 2, 2 * _SECOND), ("second", 5, 5 * _SECOND),
    ("second", 15, 15 * _SECOND), ("second", 30, 30 * _SECOND),
    ("minute", 1, _MINUTE), ("minute", 2, 2 * _MINUTE), ("minute", 5, 5 * _MINUTE),
    ("minute", 15, 15 * _MINUTE), ("minute", 30, 30 * _MINUTE),
    ("hour", 1, _HOUR), ("hour", 3, 3 * _HOUR), ("hour", 6, 6 * _HOUR),
    ("hour", 12, 12 * _HOUR),
    ("day", 1, _DAY), ("day", 2, 2 * _DAY),
    ("week", 1, _WEEK), ("week", 2, 2 * _WEEK),
    ("month", 1, 30.44 * _DAY), ("month", 3, 91.3 * _DAY), ("month", 6, 182.6 * _DAY),
    ("year", 1, 365.25 * _DAY),
)

_MONTH_NAMES = ("Jan", "Feb", "Mar", "Apr", "May", "Jun",
                "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

#: Which unit each rung subdivides into for minor ticks. A year divides into
#: months, a day into hours: the next name a reader already has for the gap.
_FINER = {"year": ("month", 1), "month": ("day", 1), "week": ("day", 1),
          "day": ("hour", 6), "hour": ("minute", 15), "minute": ("second", 15)}


@dataclass(frozen=True, slots=True)
class TimeStep:
    """One rung of the ladder: `("month", 3)` is a quarterly tick."""

    unit: str
    count: int


def to_time(value) -> _dt.datetime:
    """A datetime from a datetime, a date, an ISO 8601 string, or POSIX seconds.

    Naive throughout. A figure is a picture of one clock; carrying a timezone
    through the scale would make `map` depend on which one, and an axis that
    moves when the reader's machine is in Berlin is not an axis.
    """
    if isinstance(value, _dt.datetime):
        return value.replace(tzinfo=None) if value.tzinfo is not None else value
    if isinstance(value, _dt.date):
        return _dt.datetime(value.year, value.month, value.day)
    if isinstance(value, str):
        try:
            return _dt.datetime.fromisoformat(value.strip())
        except ValueError:
            raise ScaleError(
                f"cannot read {value!r} as a date; expected ISO 8601, "
                "like '2024-03-01' or '2024-03-01T09:30'"
            ) from None
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return _EPOCH + _dt.timedelta(seconds=float(value))
    raise ScaleError(
        f"cannot read {value!r} as a date; pass a datetime, a date, an ISO "
        "string, or POSIX seconds"
    )


def _seconds(value) -> float:
    return (to_time(value) - _EPOCH).total_seconds()


def is_time_like(value) -> bool:
    """Whether a domain end names an instant rather than a number.

    Deliberately *not* true of a bare number: `(0, 10)` is a linear domain, and
    guessing that it meant 1970 would be a very expensive kindness.
    """
    return isinstance(value, (_dt.date, _dt.datetime)) or (
        isinstance(value, str) and _parses(value))


def _parses(value: str) -> bool:
    try:
        _dt.datetime.fromisoformat(value.strip())
    except ValueError:
        return False
    return True


@dataclass(frozen=True, slots=True)
class Time(Scale):
    """Instants to millimetres, ticked on the calendar.

    The domain is held in seconds since 1970 so that `map` is arithmetic, and
    every public entry point takes and returns `datetime`s. `ticks()` walks
    calendar units rather than adding a constant, which is what puts a monthly
    tick on the first of each month in a year that contains a February.
    """

    domain: tuple[float, float] = (0.0, _DAY)
    range: Range = (0.0, 1.0)
    clamp: bool = False

    @property
    def start(self) -> _dt.datetime:
        return _EPOCH + _dt.timedelta(seconds=self.domain[0])

    @property
    def end(self) -> _dt.datetime:
        return _EPOCH + _dt.timedelta(seconds=self.domain[1])

    def map(self, value) -> float:
        d0, d1 = self.domain
        span = d1 - d0
        t = 0.5 if span == 0 else (_seconds(value) - d0) / span
        if self.clamp:
            t = min(1.0, max(0.0, t))
        return _interpolate(t, *self.range)

    def invert(self, position: float) -> _dt.datetime:
        r0, r1 = self.range
        span = r1 - r0
        if span == 0:
            return self.start
        return _EPOCH + _dt.timedelta(
            seconds=_interpolate((position - r0) / span, *self.domain))

    def step(self, count: int = 5) -> TimeStep:
        """The rung of the ladder that gives roughly `count` ticks."""
        return _pick_step(self.domain[1] - self.domain[0], count)

    def ticks(self, count: int = 5) -> tuple[_dt.datetime, ...]:
        return time_ticks(self.start, self.end, count)

    def tick_labels(self, ticks: Sequence) -> tuple[str, ...]:
        """Read off the ticks themselves, not off `step()`.

        A caller may pass `ticks=` of their own, and a set of dates says how
        coarse it is by where it lands: all on a 1 January is a yearly axis
        whatever the scale would have chosen.
        """
        values = [to_time(t) for t in ticks]
        return _labels(values, _rung_of(values),
                       self.domain[1] - self.domain[0])

    def minor_ticks(self, majors: Sequence, count: int | None = None,
                    clear: float = 0.0) -> tuple:
        """Subdivisions in the next calendar unit down -- months inside a
        year, hours inside a day -- dropped entirely if they would not clear.

        `count` is ignored: the finer unit is a name, not a division, and
        "seven pieces of a month" is not one.
        """
        if len(majors) < 2:
            return ()
        rung = self.step(len(majors))
        finer = _FINER.get(rung.unit)
        if finer is None:
            return ()
        unit, size = finer
        known = {to_time(m) for m in majors}
        out = tuple(t for t in _walk(self.start, self.end, unit, size)
                    if t not in known)
        if not out or clear <= 0:
            return out
        places = sorted([self.map(t) for t in out] + [self.map(m) for m in majors])
        if all(b - a >= clear - 1e-9 for a, b in zip(places, places[1:])):
            return out
        return ()

    def offset_label(self, ticks: Sequence) -> str | None:
        """The date these ticks are all inside, for writing once at the end.

        `Jan Apr Jul Oct` is the right set of labels for a year of data and it
        never says which year; the same axis in clock time says `09:00 12:00`
        and never says which day. Rather than repeat the missing part on every
        tick -- which is what makes a date axis unreadable -- an axis writes it
        once, small, past the last tick. matplotlib calls it an offset
        annotation, and it is the right answer.

        None when the ticks say it themselves: a yearly axis writes the years,
        and a set that crosses New Year already carries them.
        """
        values = [to_time(t) for t in ticks]
        if not values:
            return None
        unit = _rung_of(values).unit
        if unit in ("month", "week", "day"):
            years = {t.year for t in values}
            return f"{values[0].year}" if len(years) == 1 else None
        if unit in ("hour", "minute", "second"):
            days = {t.date() for t in values}
            if len(days) != 1:
                return None
            day = values[0]
            return f"{day.day} {_MONTH_NAMES[day.month - 1]} {day.year}"
        return None

    def nice(self, count: int = 5) -> "Time":
        """The domain widened to whole ticks, so the axis ends on a labelled one."""
        rung = self.step(count)
        return replace(self, domain=(_seconds(_floor_to(self.start, rung)),
                                     _seconds(_ceil_to(self.end, rung))))


def dates(domain=("1970-01-01", "1970-01-02"), range: Range = (0.0, 1.0), *,
          clamp: bool = False, nice: bool = False) -> Time:
    """A time axis over `(start, end)`.

    The ends are `datetime`s, `date`s, ISO 8601 strings or POSIX seconds, in
    any mix. `nice=True` rounds them out to whole ticks -- a series ending on
    the 27th of June then draws an axis that ends in July, which is usually
    what a monthly grid should do.
    """
    try:
        low, high = domain
    except (TypeError, ValueError):
        raise ScaleError(
            f"a time domain is a (start, end) pair, not {domain!r}") from None
    scale = Time((_seconds(low), _seconds(high)), (mm(range[0]), mm(range[1])),
                 clamp)
    return scale.nice() if nice else scale


def time_ticks(start, end, count: int = 5) -> tuple[_dt.datetime, ...]:
    """Aligned calendar ticks inside `[start, end]`, about `count` of them."""
    first, last = to_time(start), to_time(end)
    if last < first:
        first, last = last, first
    rung = _pick_step((last - first).total_seconds(), count)
    return tuple(t for t in _walk(first, last, rung.unit, rung.count))


# -- choosing and walking the ladder --------------------------------------


def _pick_step(span_seconds: float, count: int) -> TimeStep:
    """The rung whose spacing is nearest `span / count`, geometrically.

    Past a year the ladder runs out and the step goes back to 1/2/5 times a
    power of ten *years*, which is how a century-long axis gets decade ticks
    without twenty more rows in the table.
    """
    if count < 1:
        raise ScaleError(f"tick count must be at least 1, got {count}")
    want = abs(span_seconds) / count
    if want <= 0:
        return TimeStep("second", 1)
    if want > 365.25 * _DAY:
        years = want / (365.25 * _DAY)
        magnitude = 10.0 ** math.floor(math.log10(years))
        fraction = years / magnitude
        for cut, step in ((1.5, 1.0), (3.0, 2.0), (7.0, 5.0)):
            if fraction < cut:
                return TimeStep("year", max(1, int(round(step * magnitude))))
        return TimeStep("year", max(1, int(round(10.0 * magnitude))))
    best = _LADDER[0]
    for rung in _LADDER:
        # Geometric distance, so a step twice too coarse and one twice too fine
        # are equally wrong; on a linear comparison the coarse one always wins
        # and a day-long axis gets ticked every twelve hours.
        if abs(math.log(rung[2] / want)) < abs(math.log(best[2] / want)) - 1e-12:
            best = rung
    return TimeStep(best[0], best[1])


def _walk(first: _dt.datetime, last: _dt.datetime, unit: str,
          size: int) -> list[_dt.datetime]:
    """Every aligned instant of `size` `unit`s within the closed interval."""
    out: list[_dt.datetime] = []
    at = _align(first, unit, size)
    guard = 0
    while at <= last:
        if at >= first:
            out.append(at)
        at = _advance(at, unit, size)
        guard += 1
        if guard > 10000:                # a step that never advances
            break
    return out


def _align(when: _dt.datetime, unit: str, size: int) -> _dt.datetime:
    """The first aligned instant at or before `when`.

    Alignment is against the calendar, not against the data: hours land on the
    hour, quarters on January, April, July, October. That is the whole reason a
    time axis is not a linear one over seconds.
    """
    if unit == "year":
        year = when.year - (when.year % size if size > 1 else 0)
        return _dt.datetime(year, 1, 1)
    if unit == "month":
        month = ((when.month - 1) // size) * size + 1
        return _dt.datetime(when.year, month, 1)
    if unit == "week":
        day = _dt.datetime(when.year, when.month, when.day)
        return day - _dt.timedelta(days=day.weekday())      # back to Monday
    if unit == "day":
        return _dt.datetime(when.year, when.month, when.day)
    if unit == "hour":
        return when.replace(minute=0, second=0, microsecond=0,
                            hour=(when.hour // size) * size)
    if unit == "minute":
        return when.replace(second=0, microsecond=0,
                            minute=(when.minute // size) * size)
    return when.replace(microsecond=0, second=(when.second // size) * size)


def _advance(when: _dt.datetime, unit: str, size: int) -> _dt.datetime:
    if unit == "year":
        return when.replace(year=when.year + size)
    if unit == "month":
        month = when.month - 1 + size
        year = when.year + month // 12
        month = month % 12 + 1
        return _dt.datetime(year, month, min(when.day,
                                             calendar.monthrange(year, month)[1]))
    seconds = {"week": _WEEK, "day": _DAY, "hour": _HOUR,
               "minute": _MINUTE, "second": _SECOND}[unit]
    return when + _dt.timedelta(seconds=seconds * size)


def _floor_to(when: _dt.datetime, rung: TimeStep) -> _dt.datetime:
    return _align(when, rung.unit, rung.count)


def _ceil_to(when: _dt.datetime, rung: TimeStep) -> _dt.datetime:
    at = _align(when, rung.unit, rung.count)
    return at if at == when else _advance(at, rung.unit, rung.count)


# -- writing them ---------------------------------------------------------


def _rung_of(ticks: Sequence[_dt.datetime]) -> TimeStep:
    """How coarse a set of ticks is, read off where they land."""
    if not ticks:
        return TimeStep("second", 1)
    midnight = all(t.hour == 0 and t.minute == 0 and t.second == 0 for t in ticks)
    if midnight and all(t.month == 1 and t.day == 1 for t in ticks):
        return TimeStep("year", 1)
    if midnight and all(t.day == 1 for t in ticks):
        return TimeStep("month", 1)
    if midnight:
        return TimeStep("day", 1)
    if all(t.minute == 0 and t.second == 0 for t in ticks):
        return TimeStep("hour", 1)
    if all(t.second == 0 for t in ticks):
        return TimeStep("minute", 1)
    return TimeStep("second", 1)


def _labels(ticks: Sequence[_dt.datetime], rung: TimeStep,
            span_seconds: float) -> tuple[str, ...]:
    """What each tick is written as, given how coarse the set is.

    The rule is that a label says everything the *set* does not already: a
    monthly axis inside one year writes `Mar`, and the same axis spanning three
    years writes `Mar 24`, because otherwise the reader meets `Mar` twice.
    """
    unit = rung.unit
    if unit == "year":
        return tuple(f"{t.year}" for t in ticks)
    if unit in ("month", "week", "day"):
        # Whether the reader would meet the same month name twice. Counted off
        # the ticks themselves rather than off the span, because a ten-month
        # axis inside one year does not need the year on every label and an
        # eight-month one that straddles New Year does.
        crosses = len({t.year for t in ticks}) > 1
        if unit == "month":
            return tuple(f"{_MONTH_NAMES[t.month - 1]} {t.year % 100:02d}"
                         if crosses else _MONTH_NAMES[t.month - 1]
                         for t in ticks)
        return tuple(f"{t.day} {_MONTH_NAMES[t.month - 1]}" for t in ticks)
    if unit == "hour":
        return tuple(f"{t.hour:02d}:00" for t in ticks)
    if unit == "minute":
        return tuple(f"{t.hour:02d}:{t.minute:02d}" for t in ticks)
    return tuple(f"{t.hour:02d}:{t.minute:02d}:{t.second:02d}" for t in ticks)
