"""Palette stops generated by `tools/gen_palette_data.py`. Do not edit.

Every value is a published entry, converted to 8-bit hex. The maps keep an
evenly spaced subset of their 256 entries; the comment on each gives the
step and the worst CIEDE2000 error of re-interpolating the full table.
"""

from __future__ import annotations

# name -> (kind, stops)
MATPLOTLIB: dict[str, tuple[str, tuple[str, ...]]] = {
    # every 17th of 256 entries, max dE00 0.36
    'viridis': ('sequential', (
        '#440154', '#481a6c', '#472f7d', '#414487', '#39568c', '#31688e', '#2a788e', '#23888e',
        '#1f988b', '#22a884', '#35b779', '#54c568', '#7ad151', '#a5db36', '#d2e21b', '#fde725',
    )),
    # every 5th of 256 entries, max dE00 0.63
    'cividis': ('sequential', (
        '#00224e', '#002656', '#002a5f', '#002d68', '#003070', '#083370', '#163770', '#203a6f',
        '#273e6e', '#2e416d', '#34456c', '#3a486c', '#3f4c6c', '#444f6c', '#49536c', '#4e566c',
        '#535a6d', '#575d6d', '#5c616e', '#60646f', '#656870', '#696b71', '#6d6f72', '#727274',
        '#767676', '#7a7a78', '#7e7d78', '#838179', '#888578', '#8d8878', '#928c78', '#969077',
        '#9b9476', '#a09875', '#a59c74', '#aaa073', '#afa471', '#b5a86f', '#baac6d', '#bfb06b',
        '#c4b468', '#c9b965', '#cfbd62', '#d4c15f', '#dac65b', '#dfca57', '#e5cf52', '#ead34c',
        '#f0d846', '#f6dd3f', '#fce236', '#fee838',
    )),
    # every 5th of 256 entries, max dE00 0.40
    'inferno': ('sequential', (
        '#000004', '#02020c', '#050417', '#0a0722', '#10092d', '#160b39', '#1e0c45', '#260c51',
        '#2f0a5b', '#380962', '#400a67', '#490b6a', '#510e6c', '#59106e', '#61136e', '#69166e',
        '#71196e', '#781c6d', '#801f6c', '#88226a', '#902568', '#982766', '#a02a63', '#a82e5f',
        '#b0315b', '#b73557', '#bf3952', '#c63d4d', '#cc4248', '#d34743', '#d94d3d', '#df5337',
        '#e45a31', '#e9612b', '#ed6925', '#f1711f', '#f47918', '#f78212', '#f98b0b', '#fa9407',
        '#fb9d07', '#fca60c', '#fcb014', '#fbba1f', '#fac42a', '#f8cd37', '#f6d746', '#f4e156',
        '#f2ea69', '#f2f27d', '#f5f992', '#fcffa4',
    )),
    # every 17th of 256 entries, max dE00 0.33
    'plasma': ('sequential', (
        '#0d0887', '#330597', '#5002a2', '#6a00a8', '#8405a7', '#9c179e', '#b12a90', '#c33d80',
        '#d35171', '#e16462', '#ed7953', '#f68f44', '#fca636', '#fec029', '#f9dc24', '#f0f921',
    )),
    # every 5th of 256 entries, max dE00 0.38
    'magma': ('sequential', (
        '#000004', '#02020b', '#050416', '#090720', '#0e0b2b', '#140e36', '#1a1042', '#21114e',
        '#29115a', '#311165', '#390f6e', '#420f75', '#4a1079', '#52137c', '#5a167e', '#621980',
        '#6a1c81', '#721f81', '#792282', '#812581', '#892881', '#912b81', '#992d80', '#a1307e',
        '#aa337d', '#b2357b', '#ba3878', '#c23b75', '#ca3e72', '#d2426f', '#d9466b', '#e04c67',
        '#e75263', '#ec5860', '#f1605d', '#f4695c', '#f7725c', '#f97b5d', '#fb8560', '#fc8e64',
        '#fd9869', '#fea16e', '#feaa74', '#feb47b', '#febd82', '#fec68a', '#fecf92', '#fed89a',
        '#fde2a3', '#fdebac', '#fcf4b6', '#fcfdbf',
    )),
}

CRAMERI: dict[str, tuple[str, tuple[str, ...]]] = {
    # every 17th of 256 entries, max dE00 0.68
    'batlow': ('sequential', (
        '#011959', '#0d325e', '#124561', '#185562', '#26635f', '#3c6d56', '#577647', '#737e38',
        '#91862d', '#b38e2f', '#d29343', '#ed9a62', '#fba689', '#fdb2af', '#fcbfd3', '#faccfa',
    )),
    # every 17th of 256 entries, max dE00 0.90
    'batlowk': ('sequential', (
        '#04050a', '#121c2b', '#1f354b', '#304d5d', '#405c5e', '#4f6657', '#61704d', '#787c41',
        '#958939', '#b7953c', '#d89e50', '#eea570', '#f9ac92', '#fdb5b4', '#fdc0d6', '#faccfa',
    )),
    # every 17th of 256 entries, max dE00 0.91
    'batloww': ('sequential', (
        '#011959', '#0d325e', '#114561', '#175462', '#246261', '#396e59', '#53784c', '#6e823e',
        '#8e8d33', '#b1993a', '#d0a35a', '#e4aa7c', '#f3b49e', '#fdcdc9', '#ffe9e9', '#fffefe',
    )),
    # every 17th of 256 entries, max dE00 0.91
    'acton': ('sequential', (
        '#260d40', '#352253', '#423564', '#4f4775', '#5d5884', '#71618c', '#85648e', '#9b658f',
        '#b46791', '#ca7199', '#d586aa', '#db9cbd', '#e2b2cf', '#e7c7df', '#ecdaed', '#f0eafa',
    )),
    # every 17th of 256 entries, max dE00 0.49
    'bamako': ('sequential', (
        '#003b47', '#084042', '#11453d', '#1b4c37', '#28542f', '#365e26', '#47681c', '#597411',
        '#6b8005', '#818800', '#988d03', '#ae9c1b', '#c6ae39', '#dbc160', '#edd488', '#ffe5ad',
    )),
    # every 17th of 256 entries, max dE00 0.91
    'bilbao': ('sequential', (
        '#4c0001', '#65181b', '#7b2b31', '#8e3f46', '#9b5253', '#a06257', '#a46f5a', '#a77c5d',
        '#ab8860', '#ae9663', '#b5a772', '#bdb590', '#c4c0ac', '#cdcbc4', '#e1e1e1', '#ffffff',
    )),
    # every 17th of 256 entries, max dE00 0.29
    'buda': ('sequential', (
        '#b301b3', '#b31ea5', '#b4319b', '#b84294', '#bd528f', '#c2618a', '#c76f85', '#cb7e80',
        '#cf8c7c', '#d39b79', '#d7aa75', '#dab971', '#dec96d', '#e3d969', '#eceb67', '#ffff66',
    )),
    # every 17th of 256 entries, max dE00 0.54
    'davos': ('sequential', (
        '#00054a', '#091e62', '#163479', '#234a8c', '#335f98', '#43709d', '#547d9c', '#648896',
        '#74938f', '#849e89', '#99ad88', '#b4c190', '#d4dba8', '#edefc7', '#f9f9e5', '#fefefe',
    )),
    # every 17th of 256 entries, max dE00 0.43
    'devon': ('sequential', (
        '#2c1a4c', '#2a295c', '#28396c', '#274a7e', '#2a5c95', '#3669ad', '#4c77c4', '#6d87d6',
        '#8d95e3', '#a8a5ec', '#bab3f1', '#c7c2f4', '#d5d1f6', '#e3e0f9', '#f1effc', '#ffffff',
    )),
    # every 17th of 256 entries, max dE00 0.68
    'glasgow': ('sequential', (
        '#361338', '#46172b', '#541b1e', '#652211', '#723203', '#744500', '#735704', '#70681c',
        '#6a773c', '#65845d', '#60927d', '#659f9d', '#7eaeb9', '#9cbad1', '#b9c6e6', '#dbd3ff',
    )),
    # every 5th of 256 entries, max dE00 0.55
    'grayc': ('sequential', (
        '#000000', '#090909', '#111111', '#161616', '#1b1b1b', '#202020', '#242424', '#292929',
        '#2e2e2e', '#323232', '#373737', '#3b3b3b', '#404040', '#444444', '#494949', '#4d4d4d',
        '#515151', '#565656', '#5a5a5a', '#5e5e5e', '#626262', '#666666', '#6a6a6a', '#6e6e6e',
        '#717171', '#757575', '#797979', '#7d7d7d', '#808080', '#848484', '#888888', '#8d8d8d',
        '#919191', '#959595', '#9a9a9a', '#9f9f9f', '#a4a4a4', '#a9a9a9', '#aeaeae', '#b3b3b3',
        '#b8b8b8', '#bebebe', '#c4c4c4', '#cacaca', '#d0d0d0', '#d6d6d6', '#dcdcdc', '#e3e3e3',
        '#eaeaea', '#f1f1f1', '#f8f8f8', '#ffffff',
    )),
    # every 17th of 256 entries, max dE00 0.55
    'hawaii': ('sequential', (
        '#8c0273', '#901e63', '#933054', '#954147', '#97523b', '#996330', '#9c7524', '#9d8a1c',
        '#9aa122', '#8fb63c', '#80c55f', '#70d183', '#62dca9', '#63e7cf', '#84efec', '#b3f2fd',
    )),
    # every 17th of 256 entries, max dE00 0.35
    'imola': ('sequential', (
        '#1a33b3', '#203fad', '#264aa7', '#2c55a1', '#32609b', '#396b94', '#42748b', '#4d7f82',
        '#5b8d7d', '#6a9d78', '#7bae74', '#8cbf70', '#9fd26b', '#b9e468', '#dbf366', '#ffff66',
    )),
    # every 17th of 256 entries, max dE00 0.61
    'lajolla': ('sequential', (
        '#191900', '#281f09', '#3a2513', '#512d1e', '#6e362d', '#8f403d', '#b34947', '#d0554c',
        '#de6b4f', '#e38050', '#e79452', '#eba853', '#f0bd57', '#f6d66d', '#fced9c', '#fffecb',
    )),
    # every 17th of 256 entries, max dE00 0.68
    'lapaz': ('sequential', (
        '#1a0c64', '#202172', '#24347f', '#28468b', '#2e5795', '#36679d', '#4277a2', '#5285a4',
        '#6692a2', '#7c9b9e', '#94a298', '#adaa95', '#cab79d', '#e7cbb5', '#f8e0d4', '#fef2f3',
    )),
    # every 17th of 256 entries, max dE00 0.84
    'lipari': ('sequential', (
        '#031326', '#092946', '#1b4064', '#3c5478', '#575c7a', '#6b5f76', '#806070', '#97616a',
        '#b26364', '#cf695e', '#e57b62', '#ea946f', '#e6aa7f', '#e6c095', '#efdab5', '#fdf5da',
    )),
    # every 17th of 256 entries, max dE00 0.61
    'navia': ('sequential', (
        '#031327', '#052648', '#083b6a', '#105185', '#1e6491', '#28728f', '#327c89', '#3c8583',
        '#478f7d', '#549b75', '#65ab6c', '#7fbd68', '#a7d278', '#cde19b', '#e9ecbe', '#fcf4d9',
    )),
    # every 17th of 256 entries, max dE00 0.57
    'nuuk': ('sequential', (
        '#05598c', '#1e5e86', '#2f6583', '#436e82', '#587a86', '#6f878d', '#859493', '#98a097',
        '#a7aa97', '#b2b293', '#bab98d', '#c1c187', '#caca83', '#d9d988', '#eded9a', '#fefeb2',
    )),
    # every 5th of 256 entries, max dE00 0.75
    'oslo': ('sequential', (
        '#010101', '#04070b', '#060c13', '#091119', '#0c151f', '#0d1925', '#0e1c2c', '#0e2032',
        '#0f2439', '#102840', '#112c47', '#13314e', '#143555', '#163a5d', '#183e64', '#1a436c',
        '#1c4873', '#1f4c7b', '#225183', '#26568b', '#2a5b93', '#2f609b', '#3465a3', '#3b6bab',
        '#4371b2', '#4b77b9', '#537dbe', '#5b83c3', '#6388c6', '#6a8dc8', '#7091c9', '#7795c9',
        '#7d99ca', '#839dca', '#89a0ca', '#8ea4c9', '#94a8c9', '#9aacc9', '#a0afc9', '#a7b4ca',
        '#adb8cb', '#b4bdcc', '#bac2ce', '#c2c7d1', '#c9cdd4', '#d1d3d9', '#d8dade', '#e0e1e4',
        '#e8e9ea', '#eff0f1', '#f7f7f8', '#ffffff',
    )),
    # every 17th of 256 entries, max dE00 0.51
    'tokyo': ('sequential', (
        '#1c0e34', '#39173d', '#532747', '#653a4d', '#6d4b50', '#705751', '#716152', '#736a53',
        '#757654', '#788555', '#7c9859', '#84b062', '#95cb78', '#b4e69c', '#d6f6c3', '#effcdd',
    )),
    # every 5th of 256 entries, max dE00 0.58
    'turku': ('sequential', (
        '#000000', '#090908', '#111110', '#171715', '#1c1c19', '#21211e', '#262622', '#2b2b26',
        '#30302a', '#36362d', '#3b3b31', '#404034', '#454537', '#4b4a3a', '#504f3d', '#55543f',
        '#5a5a42', '#5f5f44', '#646447', '#6a6949', '#6f6e4b', '#75734e', '#7b7950', '#817e53',
        '#878356', '#8e8859', '#968e5c', '#9d9360', '#a59764', '#ad9b68', '#b59f6c', '#bca170',
        '#c3a374', '#c9a578', '#cfa67c', '#d4a780', '#daa784', '#dea889', '#e3aa8e', '#e8ac94',
        '#ecae9b', '#f0b2a2', '#f4b6aa', '#f7bbb1', '#f9c0b9', '#fbc5c0', '#fdcbc7', '#fed0ce',
        '#fed6d4', '#ffdbda', '#ffe0e0', '#ffe6e6',
    )),
    # every 17th of 256 entries, max dE00 0.66
    'bam': ('diverging', (
        '#65024b', '#8a2870', '#a9468f', '#c164a9', '#d587c1', '#e4aed6', '#f0d1e8', '#f6eaf1',
        '#f3f3ec', '#e2edd1', '#c1daa2', '#97bc6f', '#709e4b', '#508432', '#32691b', '#0d4c00',
    )),
    # every 15th of 256 entries, max dE00 0.91
    'berlin': ('diverging', (
        '#9eb0ff', '#7bacee', '#56a2d7', '#398bb4', '#2b6f8f', '#20546c', '#173a4b', '#11232c',
        '#121214', '#210b03', '#330f00', '#481502', '#63210c', '#843924', '#a25544', '#c07165',
        '#df8f89', '#ffadad',
    )),
    # every 5th of 256 entries, max dE00 0.61
    'broc': ('diverging', (
        '#2c1a4c', '#2b2154', '#2b295b', '#2a3063', '#29386a', '#283f72', '#28477a', '#2a5082',
        '#2e5889', '#346191', '#3d6a97', '#47729e', '#527ba4', '#5d84aa', '#688cb0', '#7495b6',
        '#7f9ebc', '#8ba7c2', '#97b0c8', '#a2b9ce', '#aec2d5', '#bacbdb', '#c6d4e1', '#d2dde7',
        '#dee5ec', '#e7eced', '#edefe9', '#edeee1', '#eaead6', '#e5e5cb', '#dfdfbf', '#d9d9b3',
        '#d3d3a7', '#cccc9b', '#c5c58f', '#bcbc83', '#b2b277', '#a8a86d', '#9d9d63', '#93935b',
        '#898952', '#7f7f4a', '#757542', '#6c6c3a', '#626232', '#59592a', '#505023', '#47471c',
        '#3e3e15', '#36360f', '#2e2e08', '#262600',
    )),
    # every 5th of 256 entries, max dE00 0.42
    'cork': ('diverging', (
        '#2c194c', '#2b2254', '#2b295c', '#2a3164', '#29396b', '#284073', '#28487b', '#295082',
        '#2d598a', '#336191', '#3c6997', '#45719d', '#4e79a2', '#5880a7', '#6288ad', '#6d90b2',
        '#7798b8', '#83a1be', '#8faac4', '#9bb3cb', '#a8bdd1', '#b5c7d8', '#c2d1df', '#d0dbe6',
        '#dce5eb', '#e5eced', '#e6eeea', '#e0eae1', '#d6e4d6', '#cbdccb', '#bfd4bf', '#b2ccb2',
        '#a6c4a6', '#9abb9a', '#8eb38d', '#82ab81', '#76a376', '#6b9c6a', '#60955f', '#558d55',
        '#4b864a', '#417f40', '#377836', '#2d702c', '#256823', '#1e5f1b', '#195615', '#164c11',
        '#14430d', '#123a0a', '#103107', '#0f2903',
    )),
    # every 15th of 256 entries, max dE00 0.92
    'lisbon': ('diverging', (
        '#e6e5ff', '#bdc8e7', '#96abcf', '#6f8eb8', '#4a729e', '#2b557f', '#193c5d', '#12273c',
        '#121921', '#1e1d17', '#333020', '#4d492e', '#69633f', '#877f52', '#a69e6a', '#c5be8b',
        '#e2deb1', '#ffffd9',
    )),
    # every 17th of 256 entries, max dE00 0.70
    'managua': ('diverging', (
        '#ffcf67', '#eaae5c', '#d59052', '#c17449', '#ab5c41', '#92463b', '#773339', '#602940',
        '#512d54', '#4c3d73', '#4e5593', '#556fae', '#5f89c3', '#69a6d7', '#75c5eb', '#81e7ff',
    )),
    # every 17th of 256 entries, max dE00 0.74
    'roma': ('diverging', (
        '#7e1700', '#903e0d', '#9e5c19', '#ac7726', '#ba9437', '#c8b455', '#d2d484', '#cce7b2',
        '#b1e9ce', '#89dad7', '#5dc1d3', '#3ea4c9', '#2d88be', '#236eb3', '#1951a6', '#033198',
    )),
    # every 15th of 256 entries, max dE00 0.92
    'tofino': ('diverging', (
        '#ded9ff', '#b6bced', '#8ea0dc', '#6683c6', '#4565a5', '#314c7e', '#223559', '#162136',
        '#0f151b', '#0f1b12', '#162d18', '#204524', '#2c5f31', '#3b7b40', '#579a54', '#82b66c',
        '#afce84', '#dbe69b',
    )),
    # every 17th of 256 entries, max dE00 0.98
    'vanimo': ('diverging', (
        '#ffcdfd', '#e59dda', '#ca73b9', '#ad539a', '#883977', '#5c244f', '#33172c', '#1d1418',
        '#1a1911', '#232c14', '#36491a', '#4c6924', '#62872f', '#7aa842', '#9ad068', '#befda5',
    )),
    # every 5th of 256 entries, max dE00 0.67
    'vik': ('diverging', (
        '#001261', '#011a66', '#02226b', '#022a70', '#023175', '#02397a', '#03417f', '#034984',
        '#055189', '#08598f', '#106294', '#196b9a', '#2575a1', '#337fa8', '#4289af', '#5194b6',
        '#619ebd', '#71a8c4', '#80b2ca', '#90bcd1', '#a0c5d8', '#b0cfde', '#c0d8e4', '#cfe0e8',
        '#dee6e9', '#e8e7e5', '#eee3dc', '#eedbd0', '#ecd1c3', '#e8c8b5', '#e4bea8', '#dfb49a',
        '#dbaa8d', '#d7a081', '#d39774', '#cf8e68', '#cc855d', '#c87c51', '#c47445', '#c06b3a',
        '#bc622f', '#b65824', '#af4c18', '#a5400f', '#9a3508', '#8f2b06', '#852206', '#7c1b06',
        '#731406', '#6a0d07', '#620607', '#590008',
    )),
    # every 15th of 256 entries, max dE00 0.93
    'bamo': ('cyclic', (
        '#4f3043', '#6b385f', '#8b4c7d', '#a56395', '#bc7dac', '#d09cc1', '#d9b8cb', '#d9c7ca',
        '#d4cdc2', '#c6cbb1', '#a9b68c', '#8b9a6d', '#758058', '#64694b', '#565441', '#4d443b',
        '#49383a', '#4e3042',
    )),
    # every 17th of 256 entries, max dE00 0.74
    'broco': ('cyclic', (
        '#372f38', '#363550', '#3b4a71', '#4c6790', '#6886aa', '#8aa3bf', '#adbecd', '#c9d1ce',
        '#ced0b7', '#bcbc92', '#9e9e6c', '#7e7e4c', '#615f36', '#4a462a', '#3c352b', '#372f37',
    )),
    # every 17th of 256 entries, max dE00 0.74
    'corko': ('cyclic', (
        '#3f3e3a', '#3e3d4c', '#404a68', '#4d6389', '#6581a5', '#849eba', '#a1b8c7', '#b0c8c5',
        '#a8c8b0', '#90ba91', '#73a36f', '#5a864c', '#4a6934', '#44542c', '#414730', '#3f3e3a',
    )),
    # every 17th of 256 entries, max dE00 0.74
    'romao': ('cyclic', (
        '#733957', '#7f3a41', '#8c4632', '#9c5d2b', '#af7d32', '#c3a34b', '#d3c876', '#d3dda1',
        '#bfe1bf', '#9bd4cd', '#74bbcd', '#589cc4', '#4e7cb2', '#575d96', '#654576', '#723959',
    )),
    # every 17th of 256 entries, max dE00 0.94
    'viko': ('cyclic', (
        '#4f1a3d', '#432754', '#363e71', '#355c8d', '#4d7da6', '#759ebc', '#a4b9c8', '#c9c2c0',
        '#d9b6a4', '#d59c7d', '#c57c56', '#aa5633', '#8a3320', '#6f1d20', '#5d152b', '#50193c',
    )),
}

# ColorBrewer, largest class of each scheme.
BREWER: dict[str, tuple[str, tuple[str, ...]]] = {
    'accent': ('categorical', (
        '#7fc97f', '#beaed4', '#fdc086', '#ffff99', '#386cb0', '#f0027f', '#bf5b17', '#666666',
    )),
    'blues': ('sequential', (
        '#f7fbff', '#deebf7', '#c6dbef', '#9ecae1', '#6baed6', '#4292c6', '#2171b5', '#08519c',
        '#08306b',
    )),
    'brbg': ('diverging', (
        '#543005', '#8c510a', '#bf812d', '#dfc27d', '#f6e8c3', '#f5f5f5', '#c7eae5', '#80cdc1',
        '#35978f', '#01665e', '#003c30',
    )),
    'bugn': ('sequential', (
        '#f7fcfd', '#e5f5f9', '#ccece6', '#99d8c9', '#66c2a4', '#41ae76', '#238b45', '#006d2c',
        '#00441b',
    )),
    'bupu': ('sequential', (
        '#f7fcfd', '#e0ecf4', '#bfd3e6', '#9ebcda', '#8c96c6', '#8c6bb1', '#88419d', '#810f7c',
        '#4d004b',
    )),
    'dark2': ('categorical', (
        '#1b9e77', '#d95f02', '#7570b3', '#e7298a', '#66a61e', '#e6ab02', '#a6761d', '#666666',
    )),
    'gnbu': ('sequential', (
        '#f7fcf0', '#e0f3db', '#ccebc5', '#a8ddb5', '#7bccc4', '#4eb3d3', '#2b8cbe', '#0868ac',
        '#084081',
    )),
    'greens': ('sequential', (
        '#f7fcf5', '#e5f5e0', '#c7e9c0', '#a1d99b', '#74c476', '#41ab5d', '#238b45', '#006d2c',
        '#00441b',
    )),
    'greys': ('sequential', (
        '#ffffff', '#f0f0f0', '#d9d9d9', '#bdbdbd', '#969696', '#737373', '#525252', '#252525',
        '#000000',
    )),
    'orrd': ('sequential', (
        '#fff7ec', '#fee8c8', '#fdd49e', '#fdbb84', '#fc8d59', '#ef6548', '#d7301f', '#b30000',
        '#7f0000',
    )),
    'oranges': ('sequential', (
        '#fff5eb', '#fee6ce', '#fdd0a2', '#fdae6b', '#fd8d3c', '#f16913', '#d94801', '#a63603',
        '#7f2704',
    )),
    'prgn': ('diverging', (
        '#40004b', '#762a83', '#9970ab', '#c2a5cf', '#e7d4e8', '#f7f7f7', '#d9f0d3', '#a6dba0',
        '#5aae61', '#1b7837', '#00441b',
    )),
    'paired': ('categorical', (
        '#a6cee3', '#1f78b4', '#b2df8a', '#33a02c', '#fb9a99', '#e31a1c', '#fdbf6f', '#ff7f00',
        '#cab2d6', '#6a3d9a', '#ffff99', '#b15928',
    )),
    'pastel1': ('categorical', (
        '#fbb4ae', '#b3cde3', '#ccebc5', '#decbe4', '#fed9a6', '#ffffcc', '#e5d8bd', '#fddaec',
        '#f2f2f2',
    )),
    'pastel2': ('categorical', (
        '#b3e2cd', '#fdcdac', '#cbd5e8', '#f4cae4', '#e6f5c9', '#fff2ae', '#f1e2cc', '#cccccc',
    )),
    'piyg': ('diverging', (
        '#8e0152', '#c51b7d', '#de77ae', '#f1b6da', '#fde0ef', '#f7f7f7', '#e6f5d0', '#b8e186',
        '#7fbc41', '#4d9221', '#276419',
    )),
    'pubu': ('sequential', (
        '#fff7fb', '#ece7f2', '#d0d1e6', '#a6bddb', '#74a9cf', '#3690c0', '#0570b0', '#045a8d',
        '#023858',
    )),
    'pubugn': ('sequential', (
        '#fff7fb', '#ece2f0', '#d0d1e6', '#a6bddb', '#67a9cf', '#3690c0', '#02818a', '#016c59',
        '#014636',
    )),
    'puor': ('diverging', (
        '#7f3b08', '#b35806', '#e08214', '#fdb863', '#fee0b6', '#f7f7f7', '#d8daeb', '#b2abd2',
        '#8073ac', '#542788', '#2d004b',
    )),
    'purd': ('sequential', (
        '#f7f4f9', '#e7e1ef', '#d4b9da', '#c994c7', '#df65b0', '#e7298a', '#ce1256', '#980043',
        '#67001f',
    )),
    'purples': ('sequential', (
        '#fcfbfd', '#efedf5', '#dadaeb', '#bcbddc', '#9e9ac8', '#807dba', '#6a51a3', '#54278f',
        '#3f007d',
    )),
    'rdbu': ('diverging', (
        '#67001f', '#b2182b', '#d6604d', '#f4a582', '#fddbc7', '#f7f7f7', '#d1e5f0', '#92c5de',
        '#4393c3', '#2166ac', '#053061',
    )),
    'rdgy': ('diverging', (
        '#67001f', '#b2182b', '#d6604d', '#f4a582', '#fddbc7', '#ffffff', '#e0e0e0', '#bababa',
        '#878787', '#4d4d4d', '#1a1a1a',
    )),
    'rdpu': ('sequential', (
        '#fff7f3', '#fde0dd', '#fcc5c0', '#fa9fb5', '#f768a1', '#dd3497', '#ae017e', '#7a0177',
        '#49006a',
    )),
    'rdylbu': ('diverging', (
        '#a50026', '#d73027', '#f46d43', '#fdae61', '#fee090', '#ffffbf', '#e0f3f8', '#abd9e9',
        '#74add1', '#4575b4', '#313695',
    )),
    'rdylgn': ('diverging', (
        '#a50026', '#d73027', '#f46d43', '#fdae61', '#fee08b', '#ffffbf', '#d9ef8b', '#a6d96a',
        '#66bd63', '#1a9850', '#006837',
    )),
    'reds': ('sequential', (
        '#fff5f0', '#fee0d2', '#fcbba1', '#fc9272', '#fb6a4a', '#ef3b2c', '#cb181d', '#a50f15',
        '#67000d',
    )),
    'set1': ('categorical', (
        '#e41a1c', '#377eb8', '#4daf4a', '#984ea3', '#ff7f00', '#ffff33', '#a65628', '#f781bf',
        '#999999',
    )),
    'set2': ('categorical', (
        '#66c2a5', '#fc8d62', '#8da0cb', '#e78ac3', '#a6d854', '#ffd92f', '#e5c494', '#b3b3b3',
    )),
    'set3': ('categorical', (
        '#8dd3c7', '#ffffb3', '#bebada', '#fb8072', '#80b1d3', '#fdb462', '#b3de69', '#fccde5',
        '#d9d9d9', '#bc80bd', '#ccebc5', '#ffed6f',
    )),
    'spectral': ('diverging', (
        '#9e0142', '#d53e4f', '#f46d43', '#fdae61', '#fee08b', '#ffffbf', '#e6f598', '#abdda4',
        '#66c2a5', '#3288bd', '#5e4fa2',
    )),
    'ylgn': ('sequential', (
        '#ffffe5', '#f7fcb9', '#d9f0a3', '#addd8e', '#78c679', '#41ab5d', '#238443', '#006837',
        '#004529',
    )),
    'ylgnbu': ('sequential', (
        '#ffffd9', '#edf8b1', '#c7e9b4', '#7fcdbb', '#41b6c4', '#1d91c0', '#225ea8', '#253494',
        '#081d58',
    )),
    'ylorbr': ('sequential', (
        '#ffffe5', '#fff7bc', '#fee391', '#fec44f', '#fe9929', '#ec7014', '#cc4c02', '#993404',
        '#662506',
    )),
    'ylorrd': ('sequential', (
        '#ffffcc', '#ffeda0', '#fed976', '#feb24c', '#fd8d3c', '#fc4e2a', '#e31a1c', '#b10026',
    )),
}
