"""The program that runs inside Blender.

`TEMPLATE` below is source code for a *different interpreter*. Blender ships
its own Python with `bpy`, `mathutils` and its own numpy, and it can see
nothing from this project or from the virtualenv inklet is installed in. So the
script imports nothing but the standard library and Blender's own modules, and
every parameter reaches it as a JSON literal pasted into the text rather than
as a shared object. That boundary is a feature: it is what lets the backend be
optional, and what stops a Blender upgrade from being able to break `import
inklet`. Do not try to share code across it.

Two things in here were found the hard way and are load-bearing:

*The frame is pinned to one frame.* `lineart_bake_strokes` bakes the whole
timeline, and a factory scene is 250 frames of identical geometry. Setting
`frame_start = frame_end` is a 250x saving on every bake.

*The viewport is forced into camera view.* Blender's Grease Pencil SVG exporter
projects through the 3D viewport it can find in the startup file's screen
layout, not through `scene.camera`. In background mode that viewport is
whatever the factory startup was saved with -- a three-quarter user
perspective. Line Art removes hidden lines as seen from `scene.camera`, so
leaving the viewport alone gives a drawing whose visibility and whose
projection disagree: a sphere seen head-on exports as a 2:1 ellipse. Setting
`region_3d.view_perspective = 'CAMERA'` on every VIEW_3D space makes the
exporter use the camera matrix, and then `ortho_scale` and the render
resolution mean what they say and the viewBox is the camera frame.
"""

from __future__ import annotations

import json
from typing import Any

__all__ = ["build_script", "SCRIPT_VERSION", "METADATA_MARKER", "IMPORTERS"]

#: Bump when a change in here would draw the same mesh differently. It is part
#: of the cache key, so an entry made by an older script is never served.
SCRIPT_VERSION = 5

#: The bake script appends its own report to the SVG behind this marker, so one
#: cached file carries both the drawing and what produced it.
METADATA_MARKER = "inklet-lineart "

#: Suffixes the script knows how to import. Listed here as well as in the
#: script so a caller can be refused before a subprocess is started.
IMPORTERS = ("obj", "ply", "stl", "glb", "gltf", "fbx", "x3d", "usd", "usdc", "usda")


def build_script(*, camera: dict[str, Any], lineart: dict[str, Any],
                 resolution: tuple[int, int], up_axis: str) -> str:
    """The bake program, with its parameters frozen into it as a literal.

    Returning one self-contained string is what makes the cache key honest: the
    key hashes this text, so any change to the parameters *or* to the program
    itself lands on a different cache entry with no version bookkeeping to
    forget.
    """
    params = {
        "camera": camera,
        "lineart": lineart,
        "resolution": list(resolution),
        "up_axis": up_axis,
        "version": SCRIPT_VERSION,
    }
    literal = json.dumps(params, sort_keys=True, separators=(",", ":"))
    return TEMPLATE.replace("__INKLET_PARAMS__", literal)


TEMPLATE = r'''
# Generated by inklet.three.blender. Runs inside Blender's interpreter under
# `blender -b --factory-startup --python this_file -- <mesh> <out.svg>`.
# It may import bpy, mathutils and the standard library, and nothing else.
import json
import math
import os
import shutil
import sys

import bpy
import mathutils

PARAMS = json.loads(r"""__INKLET_PARAMS__""")

# Blender's OBJ/PLY/STL importers rotate the file into Blender's z-up world.
# "y" is the OBJ convention and what almost every model from the wild uses;
# "z" means the file already agrees with Blender and nothing is rotated.
AXES = {
    "y": {"forward_axis": "NEGATIVE_Z", "up_axis": "Y"},
    "z": {"forward_axis": "Y", "up_axis": "Z"},
}


def fail(message):
    sys.stderr.write("inklet-lineart-error: " + message + "\n")
    sys.exit(3)


def import_mesh(path):
    suffix = os.path.splitext(path)[1].lower().lstrip(".")
    axes = AXES[PARAMS["up_axis"]]
    if suffix == "obj":
        bpy.ops.wm.obj_import(filepath=path, **axes)
    elif suffix == "ply":
        bpy.ops.wm.ply_import(filepath=path, **axes)
    elif suffix == "stl":
        bpy.ops.wm.stl_import(filepath=path, **axes)
    elif suffix in ("glb", "gltf"):
        # glTF is y-up by specification and its importer already rotates.
        bpy.ops.import_scene.gltf(filepath=path)
    elif suffix == "fbx":
        bpy.ops.import_scene.fbx(filepath=path)
    elif suffix == "x3d":
        bpy.ops.import_scene.x3d(filepath=path)
    elif suffix in ("usd", "usdc", "usda"):
        bpy.ops.wm.usd_import(filepath=path)
    else:
        fail("cannot import %r: unknown extension %r" % (path, suffix))


#: Every mesh is recentred and scaled into a cube this many units across
#: before the camera is placed. A cortical surface exported in native units is
#: 177 across and a CAD part in metres is 0.02, and Line Art's own constants --
#: stroke_depth_offset above all -- are absolute world distances, so the same
#: settings draw one of those beautifully and the other not at all. Normalising
#: makes `scale=` portable between models as well; the transform is reported so
#: a caller can put a 3D anchor back in the same space.
NORMAL_SPAN = 2.0


def mesh_objects(scene):
    # Sorted by name so that a scene with several bodies is walked in one
    # order, whatever the importer happened to build its collection in.
    return sorted(
        [o for o in scene.objects if o.type == "MESH"], key=lambda o: o.name
    )


def normalise(objects, depsgraph):
    """Recentre on the origin and scale into a NORMAL_SPAN cube.

    Returns the transform that was applied, so that a camera target given in
    the model's own coordinates can be moved with it.
    """
    lo, hi = world_bounds(objects, depsgraph)
    span = max(hi.x - lo.x, hi.y - lo.y, hi.z - lo.z)
    if span <= 0.0:
        fail("the mesh has no extent in any direction")
    centre = (lo + hi) * 0.5
    factor = NORMAL_SPAN / span
    move = (mathutils.Matrix.Scale(factor, 4)
            @ mathutils.Matrix.Translation(-centre))
    for obj in objects:
        obj.matrix_world = move @ obj.matrix_world
    return move, factor, centre


def world_bounds(objects, depsgraph):
    """Axis-aligned world bounds of everything, after modifiers."""
    lo = [float("inf")] * 3
    hi = [float("-inf")] * 3
    for obj in objects:
        evaluated = obj.evaluated_get(depsgraph)
        matrix = evaluated.matrix_world
        for corner in evaluated.bound_box:
            point = matrix @ mathutils.Vector(corner)
            for axis in range(3):
                lo[axis] = min(lo[axis], point[axis])
                hi[axis] = max(hi[axis], point[axis])
    if lo[0] > hi[0]:
        fail("the imported file contains no mesh geometry")
    return mathutils.Vector(lo), mathutils.Vector(hi)


def view_basis(direction, up_hint, roll):
    """Camera axes, built exactly the way `inklet.three.camera.View` builds them.

    Blender's camera looks down its own -Z with +X to the right and +Y up the
    page, and inklet's `View` has `right`, `up` and `forward` meaning the same
    three things -- so the mapping is x=right, y=up, z=-forward and the two
    backends draw the same picture from the same `Camera`.

    The pole case (looking straight down, where the world's up is parallel to
    the view) is resolved on the inklet side before the direction gets here, so
    `up_hint` is always usable.
    """
    z_axis = mathutils.Vector(direction).normalized()
    forward = -z_axis
    up = mathutils.Vector(up_hint).normalized()
    right = forward.cross(up)
    if right.length < 1e-9:
        fail("up is parallel to the view direction, so the page has no horizon")
    right = right.normalized()
    up = right.cross(forward)
    if roll:
        angle = math.radians(roll)
        cos, sin = math.cos(angle), math.sin(angle)
        right, up = (right * cos + up * sin), (up * cos - right * sin)
    return right, up, z_axis


def corners(lo, hi):
    return [
        mathutils.Vector((x, y, z))
        for x in (lo.x, hi.x) for y in (lo.y, hi.y) for z in (lo.z, hi.z)
    ]


def fit_orthographic(points, aspect, margin):
    """Smallest `ortho_scale` that holds every point, plus the margin.

    `ortho_scale` is the world width of the *wider* side of the frame, which is
    Blender's sensor_fit='AUTO' rule; the other side gets it scaled by the
    aspect ratio.
    """
    half_x = max([abs(p.x) for p in points] + [1e-6])
    half_y = max([abs(p.y) for p in points] + [1e-6])
    if aspect >= 1.0:
        scale = max(2.0 * half_x, 2.0 * half_y * aspect)
    else:
        scale = max(2.0 * half_y, 2.0 * half_x / aspect)
    return scale / max(1e-3, 1.0 - 2.0 * margin)


def fit_perspective(points, aspect, margin, fov_y):
    """Smallest eye-to-target distance that holds every point.

    The margin is taken out of the half-angles rather than added to the
    distance, so it is exactly the fraction of the frame it claims to be.
    """
    # sensor_fit is VERTICAL because inklet's Camera.fov is the vertical field of
    # view; the horizontal angle follows from the frame's aspect ratio.
    tan_y = math.tan(fov_y / 2.0) * max(1e-3, 1.0 - 2.0 * margin)
    tan_x = tan_y * aspect
    need = 1e-3
    for point in points:
        # The camera sits at +z looking towards the origin, so a point's depth
        # in front of the lens is (distance - point.z).
        need = max(need, point.z + abs(point.x) / tan_x)
        need = max(need, point.z + abs(point.y) / tan_y)
    return need


def place_camera(scene, lo, hi, move):
    spec = PARAMS["camera"]
    # An author's target and eye are in the model's own coordinates, which the
    # normalisation has just moved out from under them.
    centre = move @ mathutils.Vector(spec["target"]) if spec["target"] else (lo + hi) * 0.5
    direction = mathutils.Vector(spec["direction"]).normalized()
    x_axis, y_axis, z_axis = view_basis(direction, spec["up"], spec["roll"])
    basis = mathutils.Matrix((
        (x_axis.x, y_axis.x, z_axis.x),
        (x_axis.y, y_axis.y, z_axis.y),
        (x_axis.z, y_axis.z, z_axis.z),
    ))
    local = [basis.transposed() @ (p - centre) for p in corners(lo, hi)]
    radius = max([p.length for p in local] + [1e-6])

    data = bpy.data.cameras.new("inklet_camera")
    camera = bpy.data.objects.new("inklet_camera", data)
    scene.collection.objects.link(camera)
    scene.camera = camera
    aspect = float(PARAMS["resolution"][0]) / float(PARAMS["resolution"][1])
    report = {}

    if not spec["perspective"]:
        # sensor_fit AUTO makes ortho_scale the world width of the frame's
        # wider side, which is the rule fit_orthographic is written against.
        data.type = "ORTHO"
        data.sensor_fit = "AUTO"
        data.ortho_scale = spec["scale"] or fit_orthographic(local, aspect, spec["margin"])
        distance = radius * 3.0
        report["ortho_scale"] = data.ortho_scale
    else:
        data.type = "PERSP"
        data.sensor_fit = "VERTICAL"
        data.angle_y = math.radians(spec["fov"])
        distance = fit_perspective(local, aspect, spec["margin"], data.angle_y)
        report["distance"] = distance
        report["fov"] = spec["fov"]

    if spec["eye"]:
        # An explicit eye is a position, not just a direction: honour it.
        camera.location = move @ mathutils.Vector(spec["eye"])
    else:
        camera.location = centre + direction * distance
    camera.matrix_world = (
        mathutils.Matrix.Translation(camera.location) @ basis.to_4x4()
    )
    # Generous clipping. Line Art culls against these planes, and a near plane
    # left at the 0.1 m default quietly eats the front of a small model.
    data.clip_start = max(1e-5, (camera.location - centre).length - radius * 4.0)
    data.clip_end = (camera.location - centre).length + radius * 8.0
    report["roll"] = spec["roll"]
    report["target"] = [centre.x, centre.y, centre.z]
    report["eye"] = [camera.location.x, camera.location.y, camera.location.z]
    return camera, report


def force_camera_view(camera):
    """Point every 3D viewport in the startup screens at the camera.

    See this module's docstring: the SVG exporter projects through a viewport,
    not through the scene camera, and in background mode the viewport it finds
    is the factory startup's user perspective view.
    """
    count = 0
    for screen in bpy.data.screens:
        for area in screen.areas:
            if area.type != "VIEW_3D":
                continue
            for space in area.spaces:
                if space.type == "VIEW_3D":
                    space.camera = camera
                    space.region_3d.view_perspective = "CAMERA"
                    count += 1
    if count == 0:
        fail(
            "this Blender's startup file has no 3D viewport, so the Grease "
            "Pencil SVG exporter has no camera matrix to project through"
        )
    return count


def build_grease_pencil(scene):
    bpy.ops.object.gpencil_add(type="EMPTY")
    gp = bpy.context.active_object
    while gp.data.layers:
        gp.data.layers.remove(gp.data.layers[0])
    material = bpy.data.materials.new("inklet_lines")
    bpy.data.materials.create_gpencil_data(material)
    gp.data.materials.append(material)
    return gp, material


def add_lineart(gp, material, name, options, silhouette_only):
    layer = gp.data.layers.new(name, set_active=True)
    layer.frames.new(1)
    modifier = gp.grease_pencil_modifiers.new(name=name, type="GP_LINEART")
    modifier.source_type = "SCENE"
    modifier.target_layer = layer.info
    modifier.target_material = material
    modifier.thickness = options["thickness"]
    modifier.opacity = 1.0
    modifier.overscan = options["overscan"]
    if options["cull"] is not None:
        modifier.use_back_face_culling = options["cull"]
    # Chaining is what turns per-edge fragments into strokes a pen could have
    # drawn. split_angle=0 stops the chainer cutting a stroke at every corner.
    modifier.chaining_image_threshold = options["chain_gap"]
    modifier.split_angle = 0.0
    modifier.smooth_tolerance = options["smooth"]
    # Smooth shading is a statement that the facets are an artefact of the
    # tessellation, so honour it by not creasing across them. Left on for a
    # flat-shaded mesh, where every fold is real geometry the author modelled.
    modifier.use_crease_on_smooth = not options["shade_smooth"]
    if not options["hidden"]:
        # Line Art has no "draw through" switch. What it has is occlusion
        # levels: level 0 is what the camera can see, level 1 what is hidden
        # behind exactly one surface, and so on. Asking for 0 through 8 is an
        # x-ray in every practical case and costs nothing extra to compute.
        modifier.use_multiple_levels = True
        modifier.level_start = 0
        modifier.level_end = 8
    if silhouette_only:
        modifier.use_contour = True
        modifier.silhouette_filtering = "INDIVIDUAL"
    else:
        modifier.use_contour = options["contour"]
        modifier.use_crease = options["crease"] < 180.0
        # Blender's crease_threshold is the *dihedral* angle: 180 degrees is
        # flat and an edge creases when the angle between the faces falls
        # below the threshold. `crease_angle` is the fold, measured between
        # the face normals, which is the number an author can picture. The
        # two are complements, and confusing them inverts the control.
        modifier.crease_threshold = math.radians(180.0 - options["crease"])
        modifier.use_intersection = options["intersection"]
        modifier.use_material = options["material"]
        modifier.use_edge_mark = options["edge_marks"]
        modifier.use_loose = options["loose"]
    return modifier


def prepare_geometry(objects, options):
    for obj in objects:
        if options["subdivide"] > 0:
            modifier = obj.modifiers.new(name="inklet_subsurf", type="SUBSURF")
            modifier.levels = options["subdivide"]
            modifier.render_levels = options["subdivide"]
        if options["shade_smooth"]:
            # Mesh.shade_smooth() is one C call; the Python loop over
            # `polygons` it replaces is seconds on a 70k-face scan.
            obj.data.shade_smooth()


def annotate(path, report):
    """Append the bake report to the SVG as a comment.

    One cached file then carries both the drawing and the numbers that describe
    it -- how the camera was framed, how many strokes came out -- so a cache hit
    can answer the same questions a fresh bake can.
    """
    with open(path, "r", encoding="utf-8") as handle:
        text = handle.read()
    # An XML comment may not contain a double hyphen, and an object name in
    # the report is whatever the mesh's author called it. `\u002d` is a hyphen
    # to a JSON reader and not one to an XML parser, so escaping the second of
    # every pair keeps both happy.
    payload = json.dumps(report, sort_keys=True).replace("--", "-\\u002d")
    comment = "<!--inklet-lineart " + payload + "-->\n"
    marker = "</svg>"
    index = text.rfind(marker)
    text = text[:index] + comment + text[index:] if index >= 0 else text + comment
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)


def main():
    argv = sys.argv[sys.argv.index("--") + 1:]
    if len(argv) != 2:
        fail("expected exactly two arguments after --: <mesh> <out.svg>")
    mesh_path, out_path = argv

    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    # One frame, not the timeline's 250 identical copies of it.
    scene.frame_start = scene.frame_end = scene.frame_current = 1
    scene.render.resolution_x = PARAMS["resolution"][0]
    scene.render.resolution_y = PARAMS["resolution"][1]
    scene.render.resolution_percentage = 100
    scene.render.pixel_aspect_x = 1.0
    scene.render.pixel_aspect_y = 1.0

    import_mesh(mesh_path)
    objects = mesh_objects(scene)
    if not objects:
        fail("the imported file contains no mesh objects")
    options = PARAMS["lineart"]
    prepare_geometry(objects, options)

    depsgraph = bpy.context.evaluated_depsgraph_get()
    move, factor, centre = normalise(objects, depsgraph)
    bpy.context.view_layer.update()
    lo, hi = world_bounds(objects, depsgraph)

    # Everything the report needs about the mesh, read now and kept as plain
    # numbers and strings. Adding a Grease Pencil object and baking Line Art
    # can reallocate `bpy.data.objects`, and a Python wrapper held across that
    # is a dangling pointer -- one that usually still works, which is why the
    # segfault it eventually causes lands somewhere innocent and much later.
    subject = {
        "faces": sum(len(o.data.polygons) for o in objects),
        "objects": [str(o.name) for o in objects],
    }
    del objects

    camera, camera_report = place_camera(scene, lo, hi, move)
    force_camera_view(camera)

    gp, material = build_grease_pencil(scene)
    gp_name = str(gp.name)
    add_lineart(gp, material, "lines", options, False)
    if options["silhouette"]:
        add_lineart(gp, material, "silhouette", options, True)
    del gp, material

    bpy.ops.object.lineart_bake_strokes()

    # Re-fetch the Grease Pencil object by name rather than reusing the
    # wrapper from before the bake, for the reason given above.
    baked = bpy.data.objects[gp_name]
    strokes = {}
    for layer in baked.data.layers:
        frame = layer.frames[0]
        strokes[str(layer.info)] = {
            "strokes": len(frame.strokes),
            "points": sum(len(s.points) for s in frame.strokes),
        }
    if not any(entry["strokes"] for entry in strokes.values()):
        fail(
            "Line Art found no visible edges: the subject may be outside the "
            "camera frame, or every line type may be filtered out"
        )

    # The SVG exporter reads evaluated data. Baking can leave that cache with
    # an earlier, incomplete line layer; mark the data dirty before updating.
    baked.data.update_tag()
    baked.update_tag(refresh={"DATA"})
    bpy.context.view_layer.update()

    result = bpy.ops.wm.gpencil_export_svg(
        filepath=out_path,
        check_existing=False,
        use_fill=False,
        selected_object_type="VISIBLE",
        stroke_sample=options["sample"],
        use_normalized_thickness=False,
        use_clip_camera=True,
    )
    if "FINISHED" not in result:
        fail("the Grease Pencil SVG exporter reported %r" % (result,))

    report = {
        "blender": str(bpy.app.version_string),
        "bounds": [[lo.x, lo.y, lo.z], [hi.x, hi.y, hi.z]],
        "camera": camera_report,
        "faces": subject["faces"],
        "normalise": {
            "scale": factor,
            "centre": [centre.x, centre.y, centre.z],
            "span": NORMAL_SPAN,
        },
        "objects": subject["objects"],
        "perspective": PARAMS["camera"]["perspective"],
        "resolution": PARAMS["resolution"],
        "strokes": strokes,
        "subdivide": options["subdivide"],
    }
    annotate(out_path, report)


main()

# Leave without running CPython's finalisation. Blender 4.2 crashes in
# PyGC_Collect during Py_FinalizeEx on roughly a third of Line Art bakes of a
# convoluted mesh -- the collector reaches a bpy wrapper whose Blender-side data
# the quit path has already freed. It happens long after the SVG is on disk, so
# the artifact is correct and only the exit status lies. Skipping finalisation
# removes the whole race: this process has written its one output and has
# nothing left to clean up that the kernel will not reclaim. stdout and stderr
# are flushed by hand because os._exit does not, and Blender's per-process temp
# directory is removed by hand for the same reason -- an empty directory per
# bake would otherwise accumulate in /tmp for the life of the machine.
sys.stdout.flush()
sys.stderr.flush()
try:
    shutil.rmtree(bpy.app.tempdir, ignore_errors=True)
except Exception:
    pass
os._exit(0)
'''
