"""Generate `docs/api.md` from the package itself.

A fresh agent given this library and a figure brief read roughly 3,000 lines of
source before writing one line of its own, and said afterwards that
`src/inklet/__init__.py` was "the only complete list of the public surface". That
is true, and it is a documentation failure rather than a compliment: the
reference existed, in a form you had to be reading the source to find.

Generated rather than written, because a hand-kept reference is a reference
that disagrees with the code by the second release. `tests/test_api_docs.py`
regenerates it and fails if the committed file has drifted, so the two cannot
come apart without somebody being told.

    python tools/gen_api.py            # rewrite docs/api.md
    python tools/gen_api.py --check    # exit 1 if it would change
"""

from __future__ import annotations

import argparse
import ast
import inspect
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

import inklet  # noqa: E402
from inklet.diagnostics import RULES  # noqa: E402

OUTPUT = ROOT / "docs" / "api.md"

HEADER = """<!-- Generated by tools/gen_api.py. Do not edit by hand. -->

# `inklet` API reference

Everything `import inklet` puts in front of you, in the order the package itself
lists it. One line each: what it is, and what it is for. The full story is in
the docstring, which is what `help(inklet.link)` prints.

Two conventions run through all of it. **Millimetres are the unit** -- every
length is a number of millimetres, or a string like `"89mm"` / `"2in"` / a
`pt(9)`. And **every combinator wraps rather than rewrites**, so a handle you
took before layout still resolves inside the finished figure.
"""

FOOTER_TITLE = "\n## Diagnostic codes\n"

FOOTER_INTRO = """
What `fig.report()` can tell you. Every rule is silent on a well-formed figure
by design -- a linter that fires on good input teaches its reader to ignore it
-- so a code appearing at all means something is worth a look.

`fig.lint()` takes the thresholds as keywords: `min_font_pt`, `min_clearance_mm`,
`max_stroke_widths`, `min_contrast`, `min_dpi`. `fig.report()` takes the same
ones and formats the result.
"""


MISSING = "_(undocumented)_"


def first_paragraph(obj) -> str:
    """The docstring's opening sentence or two, on one line."""
    if isinstance(obj, (int, float)):
        return 'Numeric constant.'
    doc = inspect.getdoc(obj) or ""
    paragraph = doc.split("\n\n", 1)[0].strip()
    return " ".join(paragraph.split()) or MISSING


def methods_of(obj) -> list[tuple[str, str]]:
    """A class's public methods, in the order the source defines them.

    Without this a class arrives as a name and a one-line summary, and the way
    to find out what it *does* is to open the source -- which is exactly the
    failure this reference was written to fix. blind-02 spent twenty minutes
    looking for a way to draw a matrix on a `Panel` and concluded there was
    none, because `Panel`'s entry named none of its fourteen methods.
    """
    if not isinstance(obj, type):
        return []
    out = []
    for name, member in inspect.getmembers(obj):
        if name.startswith("_") or not callable(member):
            continue
        if getattr(member, "__objclass__", None) in (object, BaseException):
            continue
        try:
            written = f"{name}{inspect.signature(member)}".replace("(self, ", "(")
            written = written.replace("(self)", "()")
        except (TypeError, ValueError):
            written = f"{name}(...)"
        out.append((written, first_paragraph(member)))
    order = {n: i for i, n in enumerate(getattr(obj, "__dict__", {}))}
    return sorted(out, key=lambda m: order.get(m[0].split("(")[0], 999))


def signature_of(name: str, obj) -> str:
    if isinstance(obj, type):
        try:
            return f"class {name}{inspect.signature(obj)}"
        except (TypeError, ValueError):
            return f"class {name}"
    if callable(obj):
        try:
            return f"{name}{inspect.signature(obj)}"
        except (TypeError, ValueError):
            return f"{name}(...)"
    return f"{name} = {obj!r}"


def sections() -> list[tuple[str, list[str]]]:
    """`__all__`, split at the comments the source already groups it with."""
    source = (ROOT / "src" / "inklet" / "__init__.py").read_text()
    tree = ast.parse(source)
    node = next(n for n in tree.body
                if isinstance(n, ast.Assign)
                and any(getattr(t, "id", None) == "__all__" for t in n.targets))
    lines = source.splitlines()
    grouped: list[tuple[str, list[str]]] = [("Core authoring", [])]
    for line in lines[node.lineno:node.end_lineno]:
        stripped = line.strip()
        if stripped.startswith("#"):
            title = stripped.lstrip("# ").strip().capitalize()
            grouped.append((title, []))
        else:
            grouped[-1][1].extend(
                part.strip().strip('",') for part in stripped.split('",')
                if part.strip().strip('",'))
    return [(title, names) for title, names in grouped if names]


def render() -> str:
    out = [HEADER]
    for title, names in sections():
        out.append(f"\n## {title}\n")
        for name in names:
            obj = getattr(inklet, name, None)
            if obj is None:
                continue
            out.append(f"#### `{signature_of(name, obj)}`\n")
            out.append(f"{first_paragraph(obj)}\n")
            for written, summary in methods_of(obj):
                # A signature is its own documentation for `Vec2.dot` or
                # `Rect.union`; printing "(undocumented)" after it adds a
                # complaint, not information. Prose appears where prose exists.
                out.append(f"* `{written}` -- {summary}" if summary != MISSING
                           else f"* `{written}`")
            if methods_of(obj):
                out.append("")
    out.append(FOOTER_TITLE)
    out.append(FOOTER_INTRO)
    for code in sorted(RULES):
        out.append(f"#### `{code}`\n")
        out.append(f"{first_paragraph(RULES[code])}\n")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if docs/api.md is out of date")
    args = parser.parse_args()
    text = render()
    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT} is out of date; run python tools/gen_api.py")
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text)
    print(f"wrote {OUTPUT} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
