"""Generate `docs/api.md` from the package itself.

List public exports, signatures, method summaries and diagnostic codes from
the installed source. `tests/test_docs.py` verifies that the committed
reference matches the generator output.

    python tools/gen_api.py            # rewrite docs/api.md
    python tools/gen_api.py --check    # exit 1 if it would change
"""

from __future__ import annotations

import argparse
import ast
import inspect
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

import inklet  # noqa: E402
from inklet.diagnostics import RULES  # noqa: E402

OUTPUT = ROOT / "docs" / "api.md"

HEADER = """<!-- Generated by tools/gen_api.py. Do not edit by hand. -->

# `inklet` API reference

Public names exported by `inklet`, in package order, with signatures and short
descriptions. Use `help(inklet.link)`, for example, to read the full docstring.

**Numeric drawing lengths use millimetres.** Many dimension arguments also
accept strings such as `"89mm"` or `"2in"`; `pt(9)` converts 9 points to
millimetres. **Composition preserves child handles:** combinators wrap drawings
in parent nodes, so handles created before layout still resolve in the figure.
"""

FOOTER_TITLE = "\n## Diagnostic codes\n"

FOOTER_INTRO = """
Diagnostic codes returned by `fig.lint()` and formatted by `fig.report()`.
Review each finding in the context of the finished figure; passing diagnostics
does not replace visual or scientific review.

`fig.lint()` takes the thresholds as keywords: `min_font_pt`, `min_clearance_mm`,
`max_stroke_widths`, `min_contrast`, `min_dpi`. `fig.report()` takes the same
ones and formats the result.
"""


MISSING = "_(undocumented)_"


def first_paragraph(obj) -> str:
    """The docstring's opening sentence or two, on one line."""
    if isinstance(obj, (int, float)):
        return 'Numeric constant.'
    doc = inspect.getdoc(obj) or ""
    paragraph = doc.split("\n\n", 1)[0].strip()
    return " ".join(paragraph.split()) or MISSING


def methods_of(obj) -> list[tuple[str, str]]:
    """A class's public methods, in the order the source defines them.

    Include methods so readers can find operations without opening the source.
    """
    if not isinstance(obj, type):
        return []
    out = []
    for name, member in inspect.getmembers(obj):
        if name.startswith("_") or not callable(member):
            continue
        if getattr(member, "__objclass__", None) in (object, BaseException):
            continue
        try:
            written = f"{name}{inspect.signature(member)}".replace("(self, ", "(")
            written = written.replace("(self)", "()")
        except (TypeError, ValueError):
            written = f"{name}(...)"
        out.append((written, first_paragraph(member)))
    order = {n: i for i, n in enumerate(getattr(obj, "__dict__", {}))}
    return sorted(out, key=lambda m: order.get(m[0].split("(")[0], 999))


def signature_of(name: str, obj) -> str:
    if isinstance(obj, type):
        try:
            return f"class {name}{inspect.signature(obj)}"
        except (TypeError, ValueError):
            return f"class {name}"
    if callable(obj):
        try:
            return f"{name}{inspect.signature(obj)}"
        except (TypeError, ValueError):
            return f"{name}(...)"
    return f"{name} = {obj!r}"


def sections() -> list[tuple[str, list[str]]]:
    """`__all__`, split at the comments the source already groups it with."""
    source = (ROOT / "src" / "inklet" / "__init__.py").read_text()
    tree = ast.parse(source)
    node = next(n for n in tree.body
                if isinstance(n, ast.Assign)
                and any(getattr(t, "id", None) == "__all__" for t in n.targets))
    lines = source.splitlines()
    grouped: list[tuple[str, list[str]]] = [("Core authoring", [])]
    for line in lines[node.lineno:node.end_lineno]:
        stripped = line.strip()
        if stripped.startswith("#"):
            title = stripped.lstrip("# ").strip().capitalize()
            grouped.append((title, []))
        else:
            grouped[-1][1].extend(
                part.strip().strip('",') for part in stripped.split('",')
                if part.strip().strip('",'))
    return [(title, names) for title, names in grouped if names]


def render() -> str:
    out = [HEADER]
    for title, names in sections():
        out.append(f"\n## {title}\n")
        for name in names:
            obj = getattr(inklet, name, None)
            if obj is None:
                continue
            out.append(f"#### `{signature_of(name, obj)}`\n")
            out.append(f"{first_paragraph(obj)}\n")
            for written, summary in methods_of(obj):
                # A signature is its own documentation for `Vec2.dot` or
                # `Rect.union`; printing "(undocumented)" after it adds a
                # complaint, not information. Prose appears where prose exists.
                out.append(f"* `{written}` -- {summary}" if summary != MISSING
                           else f"* `{written}`")
            if methods_of(obj):
                out.append("")
    out.append(FOOTER_TITLE)
    out.append(FOOTER_INTRO)
    for code in sorted(RULES):
        out.append(f"#### `{code}`\n")
        out.append(f"{first_paragraph(RULES[code])}\n")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if docs/api.md is out of date")
    args = parser.parse_args()
    text = render()
    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT} is out of date; run python tools/gen_api.py")
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text)
    print(f"wrote {OUTPUT} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
